language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec

matrix:
  allow_failures:
    - rvm: rbx
